export const dynamic = 'force-dynamic';
export const revalidate = 0;

import OpenAI from 'openai';
import { formatPhoneNumber } from '@/helpers/common';
import { sanitizeText, formatASCIIPart, buildResumeFilename, sendError, shortenLinkedIn } from '@/helpers/endpoint';
import { buildJobDescriptionHash, buildResumeContentHash, computeJobDescriptionSimilarity } from '@/helpers/resume-history';
import { CONSTANT_USER_ROLE_ADMIN } from '@/config/constants';
import profileModel from '@/models/profile.model';
import dbConnect from '@/mongodb';
import { createResumeAcrossClusters, findDuplicateResumeAcrossClusters, listRecentResumesByProfileAcrossClusters } from '@/mongodb-resume';
import { findBlacklistedCompanyMatch } from '@/services/(endpoint)/company-blacklist/company-blacklist.controller';
import {
  claimResumeGeneration,
  reclaimResumeGeneration,
  markResumeGenerationFailed,
  markResumeGenerationReady
} from '@/services/(endpoint)/resumes/resume-registry.controller';
import { buildResumePdf } from '@/services/(endpoint)/resumes/resume-pdf';
import { extractJobDescriptionTechnicalTerms } from '@/services/(endpoint)/resumes/resume-generation-prompts';
import { getActiveUserById, getUserById } from '@/services/(endpoint)/users/user.controller';

const DUPLICATE_HISTORY_STALE_DAYS = 90;
const JOB_DESCRIPTION_SIMILARITY_THRESHOLD = 0.85;
const SIMILARITY_CHECK_RESUME_LIMIT = 100;
const RESUME_GENERATION_MODEL = 'gpt-4.1-nano';
const RESUME_GENERATION_PROMPT_VERSION = 'route-resume-v3';
const MAX_JOB_DESCRIPTION_LENGTH = 12000;
const MIN_BULLETS_PER_ROLE = 5;
const MAX_BULLETS_PER_ROLE = 12;
const MIN_SKILLS_PER_CATEGORY = 5;
const MAX_SKILLS_PER_CATEGORY = 8;

// ---------------------------------------------------------------------------
// Date / age helpers
// ---------------------------------------------------------------------------

function formatResumeDate(value) {
  const date = value ? new Date(value) : null;
  if (!date || Number.isNaN(date.getTime())) return 'a previous date';

  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  }).format(date);
}

function isResumeOlderThanRetryThreshold(existingResume) {
  const createdAt = existingResume?.created_at ? new Date(existingResume.created_at) : null;
  if (!createdAt || Number.isNaN(createdAt.getTime())) return false;
  return Date.now() - createdAt.getTime() >= DUPLICATE_HISTORY_STALE_DAYS * 86400000;
}

// ---------------------------------------------------------------------------
// Duplicate resume messaging
// ---------------------------------------------------------------------------

function buildDuplicateResumeMessage({ existingResume, currentUser, existingResumeOwner, similarityScore = 1 }) {
  const createdLabel = formatResumeDate(existingResume?.created_at);
  const isStale = isResumeOlderThanRetryThreshold(existingResume);
  const isSameUser = String(existingResume?.associatedUserId || '') === String(currentUser?._id || '');
  const ownerName = existingResumeOwner?.username?.trim() || 'another VA';

  // Similarity note is appended as a clean separate sentence at the end of
  // each message variant rather than injected mid-sentence after a date label.
  const similarityNote =
    similarityScore < 1
      ? ` A similar job description (${Math.round(similarityScore * 100)}% match) was previously used.`
      : '';

  if (isStale) {
    if (isSameUser) {
      return `You already generated this resume on ${createdLabel}. It looks older, so please review the history before generating again.${similarityNote}`;
    }
    return `This profile and job description were already used by ${ownerName} on ${createdLabel}. Please review the history before generating again.${similarityNote}`;
  }

  if (isSameUser) {
    return `You have already generated this resume on ${createdLabel}. Please visit the history.${similarityNote}`;
  }

  return `This resume was already generated by ${ownerName} on ${createdLabel}. Please visit the history.${similarityNote}`;
}

// ---------------------------------------------------------------------------
// Similarity search
// ---------------------------------------------------------------------------

async function findHighlySimilarResume({ associatedProfileId, jobDescriptionHash, jobDescription }) {
  const recentResumes = await listRecentResumesByProfileAcrossClusters({
    associatedProfileId,
    limit: SIMILARITY_CHECK_RESUME_LIMIT
  });

  let bestMatch = null;

  for (const existingResume of recentResumes) {
    // Skip exact-hash matches — those are already handled by the registry check.
    if (!existingResume?.jobDescription || existingResume.jobDescriptionHash === jobDescriptionHash) continue;
    // Skip stale resumes — they are eligible for regeneration regardless of similarity.
    if (isResumeOlderThanRetryThreshold(existingResume)) continue;

    const similarityScore = computeJobDescriptionSimilarity(jobDescription, existingResume.jobDescription);
    if (similarityScore < JOB_DESCRIPTION_SIMILARITY_THRESHOLD) continue;

    if (!bestMatch || similarityScore > bestMatch.similarityScore) {
      bestMatch = { existingResume, similarityScore };
    }
  }

  return bestMatch;
}

function cleanString(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function normalizeTechnologyPhrases(value) {
  return cleanString(value)
    .replace(/\bAIML\b/gi, 'AI/ML')
    .replace(/\bAI\s*\/?\s*ML\b/gi, 'AI/ML')
    .replace(/\bCI\s*\/?\s*CD\b/gi, 'CI/CD')
    .replace(/\bCICD\b/gi, 'CI/CD')
    .replace(/\bg\s*RPC\b/gi, 'gRPC')
    .replace(/\bgrpc\b/g, 'gRPC')
    .replace(/\bGit Hub\b/g, 'GitHub')
    .replace(/\bGit Lab\b/g, 'GitLab')
    .replace(/\bCloud Watch\b/g, 'CloudWatch')
    .replace(/\bPostgre SQL\b/g, 'PostgreSQL')
    .replace(/\bMy SQL\b/g, 'MySQL')
    .replace(/\s+/g, ' ')
    .trim();
}

function uniqueStrings(values, maxItems = Number.POSITIVE_INFINITY) {
  const results = [];
  const seen = new Set();

  for (const value of values) {
    const item = normalizeTechnologyPhrases(value);
    if (!item) continue;
    const key = item.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    results.push(item);
    if (results.length >= maxItems) break;
  }

  return results;
}

function cleanResumeLine(value) {
  let text = normalizeTechnologyPhrases(value)
    .replace(/\be\.g\.,?\s*/gi, '')
    .replace(/\band\s+and\b/gi, 'and')
    .replace(/([,.;:])\1+/g, '$1')
    .replace(/\s+([,.;:])/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();

  const openCount = (text.match(/\(/g) || []).length;
  const closeCount = (text.match(/\)/g) || []).length;
  if (openCount > closeCount) text = text.replace(/\([^()]*$/g, '').trim();
  if (closeCount > openCount) text = text.replace(/\)+$/g, '');

  text = text
    .replace(/\b(with|and|using|including)$/i, '')
    .replace(/^[,;:.-]+|[,;:.-]+$/g, '')
    .trim();

  if (!text) return '';
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function normalizeTextList(value, maxItems) {
  if (Array.isArray(value)) {
    return uniqueStrings(value.map((item) => cleanResumeLine(item)).filter(Boolean), maxItems);
  }

  if (typeof value === 'string') {
    const parts = value
      .split(/\n+/)
      .flatMap((line) => line.split(/(?:^|\s)[-*]\s+/))
      .map((item) => cleanResumeLine(item.replace(/^[\s*-]+/, '').trim()))
      .filter(Boolean);
    return uniqueStrings(parts, maxItems);
  }

  return [];
}

function normalizeSkillList(value, maxItems) {
  const items = Array.isArray(value)
    ? value
    : typeof value === 'string'
      ? value.split(/\n|,/)
      : [];

  return uniqueStrings(
    items
      .map((item) =>
        normalizeTechnologyPhrases(item)
          .replace(/_/g, ' ')
          .replace(/^[\s*-]+/, '')
          .replace(/^[^A-Za-z0-9]+|[^A-Za-z0-9+#/&.-]+$/g, '')
          .trim()
      )
      .filter(Boolean),
    maxItems
  );
}

function formatSkillCategory(value) {
  return cleanString(value)
    .replace(/_/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
    .map((word) => {
      const upper = word.toUpperCase();
      if (['API', 'APIS', 'AWS', 'CI/CD', 'CSS', 'GCP', 'HTML', 'ML', 'NLP', 'QA', 'SQL', 'UI', 'UX'].includes(upper)) {
        return upper;
      }
      if (word.includes('/') || word.includes('.') || word.includes('&')) return word;
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join(' ');
}

function normalizeTechnicalSkills(technicalSkills) {
  if (!technicalSkills || typeof technicalSkills !== 'object' || Array.isArray(technicalSkills)) {
    return {};
  }

  const normalizedCategories = Object.entries(technicalSkills).reduce((accumulator, [category, skills]) => {
    const normalizedCategory = formatSkillCategory(category);
    const normalizedSkills = normalizeSkillList(skills, MAX_SKILLS_PER_CATEGORY);
    if (normalizedCategory && normalizedSkills.length) {
      accumulator[normalizedCategory] = normalizedSkills;
    }
    return accumulator;
  }, {});

  const keptCategories = Object.entries(normalizedCategories).filter(([, skills]) => skills.length >= MIN_SKILLS_PER_CATEGORY);
  if (keptCategories.length) {
    return Object.fromEntries(keptCategories);
  }

  const fallbackSkills = uniqueStrings(
    Object.values(normalizedCategories).flat(),
    MAX_SKILLS_PER_CATEGORY
  );

  if (fallbackSkills.length >= MIN_SKILLS_PER_CATEGORY) {
    return { 'Core Technologies': fallbackSkills };
  }

  return normalizedCategories;
}

function normalizeWorkExperiences(generatedExperiences, sourceExperiences) {
  const generatedList = Array.isArray(generatedExperiences) ? generatedExperiences : [];

  return sourceExperiences.map((sourceExperience, index) => {
    const generatedExperience = generatedList[index] || {};
    let achievements = normalizeTextList(generatedExperience?.achievements, MAX_BULLETS_PER_ROLE);

    if (achievements.length > 0 && achievements.length < MIN_BULLETS_PER_ROLE) {
      const combinedRoleText = [
        generatedExperience?.summary,
        generatedExperience?.description,
        generatedExperience?.responsibilities
      ]
        .filter(Boolean)
        .join('\n');

      const supplementalLines = normalizeTextList(combinedRoleText, MAX_BULLETS_PER_ROLE).filter(
        (line) => !achievements.some((existingLine) => existingLine.toLowerCase() === line.toLowerCase())
      );

      achievements = uniqueStrings([...achievements, ...supplementalLines], MAX_BULLETS_PER_ROLE);
    }

    return {
      job_title: cleanString(generatedExperience?.job_title) || cleanString(sourceExperience?.jobTitle),
      company_name: cleanString(generatedExperience?.company_name) || cleanString(sourceExperience?.employer),
      start_date_employment: cleanString(generatedExperience?.start_date_employment) || cleanString(sourceExperience?.startDate),
      end_date_employment: cleanString(generatedExperience?.end_date_employment) || cleanString(sourceExperience?.endDate),
      achievements
    };
  });
}

function normalizeResumeResponse(rawResponse, sourceExperiences) {
  return {
    work_experiences: normalizeWorkExperiences(rawResponse?.work_experiences, sourceExperiences),
    summary: normalizeTextList(rawResponse?.summary, 6),
    technical_skills: normalizeTechnicalSkills(rawResponse?.technical_skills),
    target_company_name: cleanString(rawResponse?.target_company_name),
    target_position: cleanString(rawResponse?.target_position)
  };
}

function buildSourceExperiences(profile) {
  const profileWorkExperience = Array.isArray(profile?.profileWorkExperience) ? profile.profileWorkExperience : [];
  return profileWorkExperience.map((experience) => ({
    jobTitle: cleanString(experience?.jobTitle),
    employer: cleanString(experience?.employer),
    startDate: cleanString(experience?.startDate),
    endDate: cleanString(experience?.endDate),
    employeeType: cleanString(experience?.employeeType),
    location: cleanString(experience?.location),
    responsibilities: cleanString(experience?.responsibilities),
    description: cleanString(experience?.description),
    techStack: cleanString(experience?.techStack),
    skills: cleanString(experience?.skills)
  }));
}

function parseWorkExperienceStartDate(value) {
  const text = cleanString(value);
  if (!text) return Number.NEGATIVE_INFINITY;

  if (/present|current/i.test(text)) {
    return Date.now();
  }

  const isoMatch = text.match(/^(\d{4})(?:[-/](\d{1,2}))?(?:[-/](\d{1,2}))?/);
  if (isoMatch) {
    const date = new Date(
      Number(isoMatch[1]),
      isoMatch[2] ? Number(isoMatch[2]) - 1 : 0,
      isoMatch[3] ? Number(isoMatch[3]) : 1
    );
    if (!Number.isNaN(date.getTime())) return date.getTime();
  }

  const monthYearMatch = text.match(/^(\d{1,2})[-/](\d{4})/);
  if (monthYearMatch) {
    const date = new Date(Number(monthYearMatch[2]), Number(monthYearMatch[1]) - 1, 1);
    if (!Number.isNaN(date.getTime())) return date.getTime();
  }

  const parsed = Date.parse(text);
  if (!Number.isNaN(parsed)) return parsed;

  const yearMatch = text.match(/\b(19|20)\d{2}\b/);
  if (yearMatch) {
    return new Date(Number(yearMatch[0]), 0, 1).getTime();
  }

  return Number.NEGATIVE_INFINITY;
}

function sortWorkExperiences(experiences) {
  if (!Array.isArray(experiences)) return [];

  return [...experiences].sort((left, right) => {
    const leftTime = parseWorkExperienceStartDate(left?.startDate);
    const rightTime = parseWorkExperienceStartDate(right?.startDate);
    return rightTime - leftTime;
  });
}

function prepareResumePrompt(profile, sourceExperiences, jobDescription) {
  const jdTechnicalTerms = extractJobDescriptionTechnicalTerms(jobDescription).slice(0, 25);
  const experiencesText = sortWorkExperiences(sourceExperiences)
    .map(
      (experience) => `
${experience.jobTitle} at ${experience.employer} (${experience.startDate} - ${experience.endDate})
- Employee type: ${experience.employeeType || 'Not provided'}
- Location: ${experience.location || 'Not provided'}
- Responsibilities: ${experience.responsibilities || 'Not provided'}
- Description: ${experience.description || 'Not provided'}
- Tech stack: ${experience.techStack || 'Not provided'}
- Skills: ${experience.skills || 'Not provided'}
`.trim()
    )
    .join('\n');
  const educationText = Array.isArray(profile?.profileEducation)
    ? profile.profileEducation
        .map(
          (education) =>
            `${cleanString(education?.educationLevel)} at ${cleanString(education?.institution)} (${cleanString(education?.startDate)} - ${cleanString(education?.yearOfCompletion)})`
        )
        .filter(Boolean)
        .join('\n')
    : '';
  const technicalChecklistText = jdTechnicalTerms.length
    ? jdTechnicalTerms.map((term, index) => `${index + 1}. ${term}`).join('\n')
    : 'No clear technical terms detected.';

  return `
Act as an HR expert and resume writer with a specialization in creating ATS-friendly resumes.

Your task is to tailor the resume to the provided job description while keeping it strong, logical, and human-sounding.

1. Detail the work experience for a resume, ensuring it aligns with the provided job description.
For each job entry:
- preserve the company name, job title, and dates from the provided work history
- write strong responsibilities and notable achievements
- make the recent and most relevant roles the strongest
- keep the writing substantial, technical, detailed, and readable
- every role should contain at least 5 bullets
- for the 1 to 2 most relevant or recent roles, write 8 to 12 bullets when possible
- for older roles, write 5 to 6 bullets when possible
- each bullet should contain a concrete engineering responsibility, implementation detail, system contribution, project scope, collaboration point, or technical outcome
- bullets should usually be 20 to 36 words so they feel meaningful instead of thin
- recent roles should clearly reflect the target stack and responsibilities when it plausibly fits
- work_experiences is the PRIMARY place to reflect job-description technical terms
- when a technical term plausibly fits, place it in a work experience bullet first, not only in summary or technical_skills
- for the most relevant recent roles, explicitly weave in the important job-description stack across multiple bullets instead of listing it only in skills
- make bullets feel like real project experience instead of generic capability statements
- include concrete details such as systems built, APIs integrated, services owned, cloud patterns used, data flows supported, CI/CD or testing practices, debugging or production support work, collaboration with cross-functional teams, and implementation outcomes when relevant
- vary the angle of the bullets so the role reads as complete and detailed across ownership, implementation, architecture, collaboration, operations, and outcomes
- do not make every bullet a simple "used X" statement; explain what was built, improved, integrated, automated, migrated, supported, or optimized with those technologies

2. Summarize the profile for the resume, ensuring it aligns with the provided job description.
- summary must be an array of 6 to 8 concise bullet lines when possible
- each summary line should feel substantial and specific, not generic

3. Add technical skills, ensuring they align with the provided job description and work experience, then categorize them like:
{
  "Frontend":["skill1","skill2","skill3","skill4","skill5"],
  "Backend":["skill1","skill2","skill3","skill4","skill5"]
}
- technical_skills should contain 4 to 6 readable categories
- each kept category should contain at least 5 skills when possible

4. Get the company name and position from the job description:
{
  "target_company_name": "",
  "target_position": ""
}

Rules:
- Return valid JSON only.
- Do not invent employers, titles, dates, degrees, certifications, or fake metrics.
- Use exact technical terms from the job description when they plausibly fit the background.
- Do not leave important technical terms trapped only in summary or technical_skills when they can naturally appear in work_experiences.
- Avoid pasted job-description fragments, recruiter text, compensation text, benefits text, remote-policy text, and awkward keyword stuffing.
- Avoid stitched clauses, repeated connectors, and half-finished phrases.
- Keep the content ATS-friendly but natural and professional.
- Prefer real project-style writing over vague capability statements.
- Make the experience section the strongest part of the resume.

Important technical terms from the job description to prioritize in work_experiences when they plausibly fit:
${technicalChecklistText}

The output format is below and please respond as JSON format only:
{
  "work_experiences": [{"job_title": "","company_name": "","start_date_employment": "","end_date_employment": "","achievements": []}],
  "summary": [],
  "technical_skills": {},
  "target_company_name": "",
  "target_position": ""
}

### Here is my work experience:
[[${experiencesText}]]

### Candidate profile title:
[[${cleanString(profile?.profileTitle) || 'Not provided'}]]

### Candidate education:
[[${educationText || 'Not provided'}]]

### Here is the job description:
[[${cleanString(jobDescription).slice(0, MAX_JOB_DESCRIPTION_LENGTH)}]]
`;
}

async function getAICompletion(prompt) {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not configured');
  }

  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const completion = await openai.chat.completions.create({
    model: RESUME_GENERATION_MODEL,
    temperature: 0.45,
    response_format: { type: 'json_object' },
    max_completion_tokens: 4096,
    messages: [
      {
        role: 'system',
        content: 'Return valid JSON only. Follow the exact output schema from the user prompt.'
      },
      {
        role: 'user',
        content: prompt
      }
    ]
  });

  const rawContent = completion?.choices?.[0]?.message?.content;
  if (!rawContent) {
    throw new Error('Resume generation returned an empty response');
  }

  return JSON.parse(rawContent);
}

async function generateResumeDirect(profile, jobDescription) {
  const sourceExperiences = sortWorkExperiences(buildSourceExperiences(profile));
  const promptText = prepareResumePrompt(profile, sourceExperiences, jobDescription);
  const completionJson = await getAICompletion(promptText);
  return {
    response: normalizeResumeResponse(completionJson, sourceExperiences),
    model: RESUME_GENERATION_MODEL,
    promptText,
    promptVersion: RESUME_GENERATION_PROMPT_VERSION
  };
}

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

export const POST = async (req) => {
  let claimedRegistry = null;
  let isAdmin = false;

  try {
    await dbConnect();

    const { profileId, desc, url, userId, companyName = '' } = await req.json();

    if (!profileId) return sendError(Response, { msg: 'profileId is required' });
    if (!desc) return sendError(Response, { msg: 'Job description is required' });
    if (!userId) return sendError(Response, { msg: 'userId is required' });

    const currentUser = await getActiveUserById(userId);
    isAdmin = currentUser.role === CONSTANT_USER_ROLE_ADMIN;

    const profile = await profileModel.findById(profileId);
    if (!profile) return sendError(Response, { msg: 'Profile not found' });

    const blacklistedCompany = await findBlacklistedCompanyMatch({
      companyName,
      jobDescription: desc,
      url
    });

    if (blacklistedCompany) {
      return sendError(Response, {
        code: 409,
        msg: `Resume generation is blocked for blacklisted company "${blacklistedCompany.companyName}". Please do not apply for this company.`
      });
    }

    const jobDescriptionHash = buildJobDescriptionHash(desc);

    if (!isAdmin) {
      const similarResumeMatch = await findHighlySimilarResume({
        associatedProfileId: profileId,
        jobDescriptionHash,
        jobDescription: desc
      });

      if (similarResumeMatch) {
        const existingResumeOwner = similarResumeMatch.existingResume?.associatedUserId
          ? await getUserById(similarResumeMatch.existingResume.associatedUserId)
          : null;

        return sendError(Response, {
          code: 409,
          msg: buildDuplicateResumeMessage({
            existingResume: similarResumeMatch.existingResume,
            currentUser,
            existingResumeOwner,
            similarityScore: similarResumeMatch.similarityScore
          })
        });
      }

      const registryClaim = await claimResumeGeneration({
        associatedProfileId: profileId,
        associatedUserId: userId,
        jobDescriptionHash
      });

      if (registryClaim.state === 'GENERATING') {
        return sendError(Response, {
          code: 409,
          msg: 'Resume generation is already in progress for this profile and job description. Please check the history shortly.'
        });
      }

      if (registryClaim.state === 'READY') {
        if (isResumeOlderThanRetryThreshold(registryClaim.entry)) {
          const reclaimedRegistry = await reclaimResumeGeneration({
            registryId: registryClaim.entry?._id,
            associatedUserId: userId
          });

          if (!reclaimedRegistry) {
            throw new Error('Failed to reopen old resume history for regeneration.');
          }

          claimedRegistry = reclaimedRegistry;
        } else {
          const existingResumeOwner = registryClaim.entry?.associatedUserId
            ? await getUserById(registryClaim.entry.associatedUserId)
            : null;

          return sendError(Response, {
            code: 409,
            msg: buildDuplicateResumeMessage({
              existingResume: registryClaim.entry,
              currentUser,
              existingResumeOwner
            })
          });
        }
      }

      claimedRegistry = claimedRegistry || registryClaim.entry;
    }

    const { response: completion, model, promptText, promptVersion } = await generateResumeDirect(profile, desc);

    const addr = profile.profileAddress || {};
    const address =
      addr.street || addr.city || addr.state || addr.zip
        ? [addr.street, addr.city, addr.state, addr.zip].filter(Boolean).join(', ')
        : '';

    const data = {
      name: sanitizeText(profile.profileName),
      mobile: sanitizeText(formatPhoneNumber(profile.profileMobile)),
      email: sanitizeText(profile.profileEmail),
      linkedin: sanitizeText(shortenLinkedIn(profile.profileLinkedIn)),
      address: sanitizeText(address),
      education: profile.profileEducation
    };

    const r = { ...data, ...completion };
    const profileTemplate = profile?.profileTemplate || 'template1';
    const resume_name = buildResumeFilename({
      name: formatASCIIPart(r.name),
      role: r.target_position,
      company: formatASCIIPart(r.target_company_name)
    });
    const resumeContentHash = buildResumeContentHash(completion);

    const resumeData = {
      companyName: r.target_company_name,
      jobTitle: r.target_position,
      jobLink: url,
      jobDescription: desc,
      jobDescriptionHash,
      resumePrompt: `[${promptVersion}]\n${promptText}`,
      resumeResponse: completion,
      resumeContentHash,
      resumeBuiltModel: model,
      resumeFileName: resume_name,
      associatedUserId: userId,
      associatedProfileId: profileId
    };

    const duplicateResume = isAdmin
      ? null
      : await findDuplicateResumeAcrossClusters({
          associatedProfileId: profileId,
          jobDescriptionHash,
          resumeContentHash
        });

    let createdResume = duplicateResume;
    if (!duplicateResume) {
      createdResume = await createResumeAcrossClusters(resumeData);
    }

    if (!isAdmin) {
      await markResumeGenerationReady({
        registryId: claimedRegistry?._id,
        associatedUserId: userId,
        companyName: resumeData.companyName,
        jobTitle: resumeData.jobTitle,
        resumeId: createdResume?._id ? String(createdResume._id) : '',
        storageClusterKey: createdResume?.storageClusterKey || ''
      });
    }

    const pdfBytes = await buildResumePdf(r, profileTemplate);

    return new Response(new Uint8Array(Buffer.from(pdfBytes)), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${resume_name}.pdf"`
      }
    });
  } catch (error) {
    // Always attempt to mark the registry entry as failed when one was claimed.
    // For admin requests claimedRegistry is null, so this is a safe no-op.
    await markResumeGenerationFailed({
      registryId: claimedRegistry?._id,
      errorMessage: error?.message || 'Unknown error'
    });

    // Admin errors never touch the registry, so log them separately to ensure
    // they surface in server logs rather than being silently swallowed.
    if (isAdmin) {
      console.error('[resume:admin] Unhandled error during generation:', error);
    } else {
      console.error('[resume] Unhandled error during generation:', error);
    }

    return sendError(Response, { msg: error?.message || 'Unknown error' });
  }
};
